### ISSUE TITLE
A few problems with todomvc demo

### ISSUE THREAD

**Issue by scriptype** [nuejs/www#18]
Hi thanks for the effort you put in this project! The philosophy behind it is certainly interesting for me.

While checking the todomvc demo, I've noticed 2 problems:

1) "x items left" counter in the footer gets out of sync with the actual number of items.

This gets fixed when you change view to filter `Active` or `Completed` items, or add a new item. Removing an item or making it `done` doesn't affect the number.

I couldn't catch any outstanding part in the https://github.com/nuejs/www/blob/master/todomvc/todomvc-compact.nue that would cause this problem. So I thought this might be indicating a problem beyond this demo.

2) The "source code" link in the page footer is directed to a 404.

Maybe because of a file renaming? (todo-compact.nue -> todomvc-compact.nue)

**Comment by tipiirai** [comment]
Thanks! Will check this out

**Comment by tipiirai** [comment]
These issues are now fixed. See: https://nuejs.org/todomvc/

Thank you!
