### ISSUE TITLE
Is there any plans for translating documentation to other languages?

### ISSUE THREAD

**Issue by MichaelYuhe** [nuejs/www#19]
Would love to contribute to add a Chinese translation if there is a plan for it.

**Comment by tipiirai** [comment]
WOW. This would be awesome! However, this would mean that there are two versions of the website that must be kept in sync all the time. I fear this leads to many problems and starts taking my time, which should be fully on coding at this stage of the product. Any suggestions to deal with this issue?

**Comment by diomed** [comment]
https://crowdin.com/page/open-source-project-setup-request

**Comment by tipiirai** [comment]
I think the timing for the translation project is when [Nuekit](https://nuejs.org/tools/#nuekit) published. After that anyone can run and develop this website locally.

**Comment by brynne8** [comment]
> I think the timing for the translation project is when [Nuekit](https://nuejs.org/tools/#nuekit) published. After that anyone can run and develop this website locally.

Maybe it's time to start the translation project.

**Comment by tipiirai** [comment]
I feel this is still too early. The website is not converted to the latest Nuekit and there is so much new content coming up (like Nuemark) and fundamental things are still shaping up. I'm not sure how we can keep up with the translation until the basework is fully implemented for internationalization. I think we should also add some features to Nuekit to help with internationalization. 

Hope you don't get me wrong. Internationalization is important and I'm sincerely thankful that you are willing to help on this one!

**Comment by tipiirai** [comment]
btw: Are you talking about Chinese translation?

**Comment by brynne8** [comment]
> btw: Are you talking about Chinese translation?

Yes, we both speak Chinese.
