### ISSUE TITLE
关于源码问题！

### ISSUE THREAD

**Issue by lililililli1** [nuejs/www#31]
你好！我是一名中国的学生我对Nue.js很期待！但是很多人说Nue的源代码和Vue2的源代码很类似，请问您借鉴了Vue2的源码吗？

**Comment by tipiirai** [comment]
Vue source code is completely different from Nue. It's like night and day. Here's how the difference looks like if you zoom out:

<img width="1390" alt="image" src="https://github.com/nuejs/www/assets/169330/e5151d71-923e-4cf3-a2fa-eb563ac69018">
