### ISSUE TITLE
Typo on the Why Nue? page

### ISSUE THREAD

**Issue by IsmailYaman** [nuejs/www#32]
It says "It’s a work im progress with the following release schedule" but should be "It’s a work in progress with the following release schedule"
![nue](https://github.com/nuejs/www/assets/25452426/2e7a4d99-a0a7-4028-8639-357d3b5fba9b)

**Comment by tipiirai** [comment]
This is now fixed. Thanks!

Sorry — this took some time. Been busy doing the next major release.
