### ISSUE TITLE
Optimize blog article `Tailwind vs. Semantic CSS`

### ISSUE THREAD

**Issue by mariohamann** [nuejs/www#56]
Hi there,

your article on `Tailwind vs. Semantic CSS` currently gets some traction.

1. I felt the urge to have a deeper look into it, as you stated it as a "study [that] compares two websites with identical design". I think there are several problems, as the websites clearly don't have an identical design and therefore this comparison lacks validity, see my blog article: https://mariohamann.com/test-quality-vs-bashing-tailwindcss
2. You're claiming that you don't need JS tooling in the Semantic version, but don't call out, that you're using `nuemark` which is a JS library, isn't it?

I would love to see either the article more nuanced or the website being a more exact copy of the original.

Thanks! :)

**Comment by tipiirai** [comment]
Thanks for the article @mariohamann! I see your point. What if I replace the word "identical" with "close enough design to getting the idea of the differences" <-- very bad wording right there, but something like that. 

The tooling refers to CSS tooling. Standard CSS needs no processing so any CSS-in-JS layer in between (like Tailwind) can be dropped.

**Comment by AleksandrZhukov** [comment]
I'm not a fan of Tailwind, but don't like when people manipulate information in their advertisements

Responsiveness of Semantic CSS blog version is terrible, video ↓ 
Please make it really close to Tailwind version, don't lie to your potential users

https://github.com/nuejs/www/assets/8876116/35d75389-8867-42d7-87eb-d01ef021b241

**Comment by tipiirai** [comment]
Thanks! Curious: what sort of concerns do you have about the marketing strategies of the Tailwind team?
